### ISSUE TITLE
FLOPs of ShiftNet-A, B, C?

### ISSUE THREAD

**Issue by iamhankai** [alvinwan/shiftresnet-cifar#6]
The parameters of ShiftNet is given in the original paper, but FLOPs is not. Could you provide the FLOPs of ShiftNet-A, B, C? I'll cite your paper :)

**Comment by alvinwan** [comment]
I know this is late but thought I'd respond for posterity. I've asked a collaborator for the relevant codebase/checkpoints and will update with a link in the README if I get a hold of them!
