### ISSUE TITLE
Broken link to CIFAR100 pretrained weights 

### ISSUE THREAD

**Issue by LinxiFan** [alvinwan/shiftresnet-cifar#7]
Link to CIFAR100 pretrained weight is broken: https://drive.google.com/drive/u/1/folders/1unOPMsQDagcDa8gI5kFvQ0VH84N7h1V2

It says the folder is moved to Trash by the owner. 

Also could you please provide pretrained ImageNet weights too? Thanks!

**Comment by alvinwan** [comment]
Here’s the correct link: https://drive.google.com/open?id=1zjAfTdMlN_EeWxUFD7VSDOak8S1ebzo9, I removed that faulty link from the readme.

I've asked the first author for ImageNet weights (that shiftnet was a different codebase/checkpoints); will update the README if he still has them!
